export const emailContent = {
  'board-update': `Subject: Monthly Financial Update - BUILDING_NAME - December 2024

Dear Board Members,

I am pleased to present the December 2024 financial update for BUILDING_NAME.

**Reserve Fund Status:**
Current Balance: $CURRENT_RESERVE
Target Balance: $TARGET_RESERVE
Funding Level: RESERVE_HEALTH% of recommended target

**Monthly Variance Analysis:**
December showed a variance of $MONTHLY_VARIANCE_AMOUNT VARIANCE_DIRECTION budget, primarily due to unscheduled maintenance expenses.

**Critical Action Items:**
• Roof replacement scheduled for Q2 2025 ($UPCOMING_EXPENSE_COST)
• Reserve funding shortfall requires immediate attention
• Recommend increasing monthly contributions by $35/unit

**AI Risk Assessment:**
Current risk level: RISK_LEVEL
Recommended action: Board resolution for contribution increase at next meeting

Please review the attached detailed financial analysis. I recommend scheduling a special meeting to discuss funding strategies.

Best regards,
PROPERTY_MANAGER_NAME

Generated by ReserveIQ AI | Confidence: 94%`,

  'owner-announcement': `Subject: Important Building Update - BUILDING_NAME

Dear Fellow Homeowners,

Your Board of Directors wants to keep you informed about important developments in our building community.

**Building Updates:**
• Our recent reserve fund analysis shows we're currently at RESERVE_HEALTH% of recommended funding levels
• We're proactively planning for upcoming maintenance to protect our investment
• Building operations continue smoothly with no major service disruptions

**Upcoming Projects:**
We're preparing for our UPCOMING_EXPENSE_ITEM project scheduled for UPCOMING_EXPENSE_TIMELINE. This planned maintenance will help preserve our building's value and prevent more costly emergency repairs.

**Financial Transparency:**
Our current reserve balance is $CURRENT_RESERVE. We're committed to maintaining strong financial health while keeping monthly fees reasonable.

**How You Can Stay Informed:**
• Attend board meetings (next meeting: January 15, 2025)
• Review financial reports posted in the lobby
• Contact any board member with questions or concerns

We appreciate your continued trust in our stewardship of our shared investment.

Warm regards,
BUILDING_NAME Board of Directors

Powered by ReserveIQ Transparency Tools`,

  'fee-increase-notice': `Subject: IMPORTANT: Monthly Fee Adjustment - Effective March 1, 2025

Dear BUILDING_NAME Homeowners,

After careful analysis and planning, your Board of Directors has approved a monthly maintenance fee adjustment effective March 1, 2025.

**The Numbers:**
Current monthly fee: $XXX per unit
New monthly fee: $XXX per unit (increase of $35/unit)
Annual impact: $420 per unit

**Why This Increase is Necessary:**

1. **Proactive Reserve Planning:**
   Our AI analysis shows we need to strengthen reserves for upcoming UPCOMING_EXPENSE_ITEM ($UPCOMING_EXPENSE_COST)

2. **Prevent Special Assessments:**
   This modest increase prevents a potential $SPECIAL_ASSESSMENT_PER_UNIT special assessment per unit

3. **Market Comparison:**
   Even with this increase, our fees remain competitive with similar buildings in our area

**Your Investment Protection:**
This decision protects your property value by:
• Maintaining building systems before they fail
• Avoiding emergency repair costs
• Keeping our building competitive in the market

**Timeline:**
• January 15: Board resolution approved
• February 1: 30-day notice period begins
• March 1: New fees take effect

**Questions?**
We encourage you to attend our February board meeting or contact any board member. We're committed to transparency in all our decisions.

Thank you for your understanding and continued investment in our community.

Respectfully,
BUILDING_NAME Board of Directors

This analysis powered by ReserveIQ Financial Intelligence`,

  'emergency-notification': `Subject: URGENT: Building Emergency - Immediate Action Required

Dear BUILDING_NAME Residents,

We are currently experiencing a building emergency that requires immediate attention and your cooperation.

**SITUATION:**
Water main break in the basement - Building water supply temporarily shut off

**IMMEDIATE IMPACT:**
• No water service to all units
• Elevators may be affected
• Parking garage partially flooded

**WHAT WE'RE DOING:**
✅ Emergency repair crews dispatched (ETA: 2 hours)
✅ Water restoration crews on standby
✅ Building management monitoring 24/7
✅ Insurance company notified

**WHAT YOU NEED TO DO:**
• Stay in your unit unless directed otherwise
• Conserve any stored water
• Avoid using the parking garage (Level B1)
• Monitor your phone/email for updates

**ESTIMATED RESOLUTION:**
Water service restoration: 4-6 hours
Full building systems: 8-12 hours

**EMERGENCY CONTACTS:**
Building Emergency Line: EMERGENCY_PHONE_1
Property Management: EMERGENCY_PHONE_2
Board President: EMERGENCY_PHONE_3

**NEXT UPDATE:**
We will send another update within 2 hours or sooner if the situation changes.

We understand this is disruptive and apologize for the inconvenience. Our priority is resolving this safely and quickly.

BUILDING_NAME Board of Directors
Property Management Team

Emergency protocols managed by ReserveIQ Crisis Systems`,

  'annual-meeting': `Subject: Annual General Meeting - BUILDING_NAME - March 15, 2025

Dear Unit Owners,

You are cordially invited to attend the Annual General Meeting of BUILDING_NAME Condominium Corporation.

**MEETING DETAILS:**
Date: Saturday, March 15, 2025
Time: 2:00 PM - 4:00 PM
Location: Building Party Room
Backup: Virtual attendance available

**AGENDA HIGHLIGHTS:**
1. Financial Review & 2024 Performance
2. Reserve Fund Analysis & Future Planning
3. Board Election (3 positions available)
4. 2025 Budget Approval
5. Major Project Updates
6. Q&A Session

**KEY DECISIONS:**
• Approval of 2025 operating budget
• Reserve fund contribution levels
• Authorization for UPCOMING_EXPENSE_ITEM project
• Election of board members

**YOUR PARTICIPATION MATTERS:**
This meeting shapes decisions affecting your investment and your home. Your voice and your vote count.

**FINANCIAL OVERVIEW:**
• Current reserve health: RESERVE_HEALTH%
• Proposed budget increase: 3.2%
• Major projects planned: $UPCOMING_EXPENSE_COST

**MEETING MATERIALS:**
Detailed financial statements, reserve study summary, and budget documents will be available 7 days before the meeting at WEBSITE_URL or in the lobby.

**PROXY VOTING:**
If you cannot attend, proxy forms are available from property management. Deadline for proxy submission: March 12, 2025.

**VIRTUAL ATTENDANCE:**
Login details will be sent to registered participants 24 hours before the meeting.

We encourage all owners to participate in this important governance process.

Respectfully,
BUILDING_NAME Board of Directors

Meeting management powered by ReserveIQ Governance Tools`,
};
