export const emailContent = {
  // 1. Board Update
  'board-update': `Subject: Monthly Financial Update – Maple Heights Condominiums – December 2024

Dear Board Members,

I am pleased to present the December 2024 financial update for Maple Heights Condominiums.

**Reserve Fund Status:**
Current Balance: $125,000  
Target Balance: $170,000  
Funding Level: 73.5% of recommended target

**Monthly Variance Analysis:**
December showed a variance of $12,500 over budget, primarily due to unscheduled maintenance expenses.

**Critical Action Items:**
• Roof replacement scheduled for Q2 2025 ($85,000)  
• Reserve funding shortfall requires immediate attention  
• Recommend increasing monthly contributions by $35/unit

**AI Risk Assessment:**
Current risk level: LOW  
Recommended action: Board resolution for contribution increase at next meeting

Please review the attached detailed financial analysis. I recommend scheduling a special meeting to discuss funding strategies.

Best regards,  
Sarah Chen

Generated by ReserveIQ AI | Confidence: 94%`,

  // 2. Owner Announcement
  'owner-announcement': `Subject: Important Building Update – Maple Heights Condominiums

Dear Fellow Homeowners,

Your Board of Directors wants to keep you informed about important developments in our building community.

**Building Updates:**
• Our recent reserve fund analysis shows we're currently at 73.5% of recommended funding levels  
• We're proactively planning for upcoming maintenance to protect our investment  
• Building operations continue smoothly with no major service disruptions

**Upcoming Projects:**
We're preparing for our Roof Replacement project scheduled in 18 months. This planned maintenance will help preserve our building's value and prevent more costly emergency repairs.

**Financial Transparency:**
Our current reserve balance is $125,000. We're committed to maintaining strong financial health while keeping monthly fees reasonable.

**How You Can Stay Informed:**
• Attend board meetings (next meeting: January 15, 2025)  
• Review financial reports posted in the lobby  
• Contact any board member with questions or concerns

We appreciate your continued trust in our stewardship of our shared investment.

Warm regards,  
Maple Heights Condominiums Board of Directors

Powered by ReserveIQ Transparency Tools`,

  // 3. Fee Increase Notice
  'fee-increase-notice': `Subject: IMPORTANT: Monthly Fee Adjustment – Effective March 1, 2025

Dear Maple Heights Condominiums Homeowners,

After careful analysis and planning, your Board of Directors has approved a monthly maintenance fee adjustment effective March 1, 2025.

**The Numbers:**
Current monthly fee: $425 per unit  
New monthly fee: $460 per unit (increase of $35/unit)  
Annual impact: $420 per unit

**Why This Increase is Necessary:**

1. **Proactive Reserve Planning:**  
   Our AI analysis shows we need to strengthen reserves for upcoming Roof Replacement ($85,000)

2. **Prevent Special Assessments:**  
   This modest increase prevents a potential $545 special assessment per unit

3. **Market Comparison:**  
   Even with this increase, our fees remain competitive with similar buildings in our area

**Your Investment Protection:**  
• Maintaining building systems before they fail  
• Avoiding emergency repair costs  
• Keeping our building competitive in the market

**Timeline:**  
• January 15: Board resolution approved  
• February 1: 30-day notice period begins  
• March 1: New fees take effect

**Questions?**  
We encourage you to attend our February board meeting or contact any board member. We're committed to transparency in all our decisions.

Thank you for your understanding and continued investment in our community.

Respectfully,  
Maple Heights Condominiums Board of Directors

This analysis powered by ReserveIQ Financial Intelligence`,

  // 4. Emergency Notification
  'emergency-notification': `Subject: URGENT: Building Emergency – Immediate Action Required

Dear Maple Heights Condominiums Residents,

We are currently experiencing a building emergency that requires immediate attention and your cooperation.

**SITUATION:**  
Water main break in the basement – Building water supply temporarily shut off

**IMMEDIATE IMPACT:**  
• No water service to all units  
• Elevators may be affected  
• Parking garage partially flooded

**WHAT WE’RE DOING:**  
✅ Emergency repair crews dispatched (ETA: 2 hours)  
✅ Water restoration crews on standby  
✅ Building management monitoring 24/7  
✅ Insurance company notified

**WHAT YOU NEED TO DO:**  
• Stay in your unit unless directed otherwise  
• Conserve any stored water  
• Avoid using the parking garage (Level B1)  
• Monitor your phone/email for updates

**ESTIMATED RESOLUTION:**  
Water service restoration: 4–6 hours  
Full building systems: 8–12 hours

**EMERGENCY CONTACTS:**  
Building Emergency Line: [XXX-XXX-XXXX]  
Property Management: [XXX-XXX-XXXX]  
Board President: [XXX-XXX-XXXX]

**NEXT UPDATE:**  
We will send another update within 2 hours or sooner if the situation changes.

We understand this is disruptive and apologize for the inconvenience. Our priority is resolving this safely and quickly.

Maple Heights Condominiums Board of Directors  
Property Management Team

Emergency protocols managed by ReserveIQ Crisis Systems`,

  // 5. Annual Meeting
  'annual-meeting': `Subject: Annual General Meeting – Maple Heights Condominiums – March 15, 2025

Dear Unit Owners,

You are cordially invited to attend the Annual General Meeting of Maple Heights Condominiums Condominium Corporation.

**MEETING DETAILS:**  
Date: Saturday, March 15, 2025  
Time: 2:00 PM – 4:00 PM  
Location: Building Party Room (virtual backup available)

**AGENDA HIGHLIGHTS:**  
1. Financial Review & 2024 Performance  
2. Reserve Fund Analysis & Future Planning  
3. Board Election (3 positions available)  
4. 2025 Budget Approval  
5. Major Project Updates  
6. Q&A Session

**KEY DECISIONS:**  
• Approval of 2025 operating budget  
• Reserve fund contribution levels  
• Authorization for Roof Replacement project  
• Election of board members

**YOUR PARTICIPATION MATTERS:**  
This meeting shapes decisions affecting your investment and your home. Your voice and your vote count.

**FINANCIAL OVERVIEW:**  
• Current reserve health: 73.5%  
• Proposed budget increase: 3.2%  
• Major projects planned: $85,000

**MEETING MATERIALS:**  
Detailed financial statements, reserve study summary, and budget documents will be available 7 days before the meeting at [Website URL] or in the lobby.

**PROXY VOTING:**  
If you cannot attend, proxy forms are available from property management. Deadline for proxy submission: March 12, 2025.

**VIRTUAL ATTENDANCE:**  
Login details will be sent to registered participants 24 hours before the meeting.

Respectfully,  
Maple Heights Condominiums Board of Directors

Meeting management powered by ReserveIQ Governance Tools`,

  // 6. Maintenance Notice
  'maintenance-notice': `Subject: Scheduled Maintenance – Maple Heights Condominiums – [Date Range]

Body:  
Dear Residents / Board Members,

This notice is to inform you of scheduled maintenance work at Maple Heights Condominiums that will take place from [Start Date] to [End Date].

**Maintenance Details:**  
- **Work Type:** [Maintenance Type]  
- **Areas Affected:** [Specific Areas/Units]  
- **Schedule:** [Start Time] to [End Time], [Days of Week]  
- **Contractor:** [Contractor Name]

**What to Expect:**  
- [Expected Impact 1]  
- [Expected Impact 2]  
- [Expected Impact 3]

**Resident Guidelines:**  
- Please ensure clear access to [Relevant Areas]  
- [Any specific resident actions required]  
- Questions or concerns should be directed to [Contact Information]

**Emergency Contact During Work Hours:**  
[Contractor Contact] – [Phone Number]  
Sarah Chen – [Phone Number]

We appreciate your patience and cooperation during this necessary maintenance work.

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Contact Information]`,

  // 7. Compliance Reminder
  'compliance-reminder': `Subject: URGENT: Reserve Fund Study Deadline – Maple Heights Condominiums

Body:  
Dear Board Members,

This is an important reminder regarding upcoming compliance deadlines for Maple Heights Condominiums.

**IMMEDIATE ACTION REQUIRED:**

**Compliance Item:** Reserve Fund Study  
**Deadline:** 2025-03-15 – 265 days remaining  
**Consequences of Non-Compliance:** [Penalties/Fines]  
**Estimated Fine if Missed:** $[Amount]

**Required Actions:**  
1. Approve new budget  
2. Select funding strategy  
3. Complete Parking Garage Waterproofing

**Documents Needed:**  
- Updated Reserve Study  
- Engineer’s Certification  
- Board Resolution

**Next Steps:**  
- Board review of compliance plan – Due: 2025-02-20  
- Submit engineer documents – Due: 2025-02-28  
- Final submission – Due: 2025-03-01

**Your Approval Needed:**  
Please confirm your approval by 2025-02-15.

**Contact Information:**  
[Email Address] | [Phone Number]

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Phone Number]`,

  // 8. Reserve Status
  'reserve-status': `Subject: Reserve Study Update – Maple Heights Condominiums Financial Health Report

Body:  
Dear Board Members,

I'm pleased to provide you with our quarterly reserve fund analysis for Maple Heights Condominiums.

**RESERVE FUND SUMMARY:**  
- **Current Balance:** $125,000  
- **Target Balance:** $170,000  
- **Funding Status:** 73.5% funded  
- **Health Rating:** Concerning

**KEY FINDINGS:**  
- 2025: Roof Replacement – $85,000  
- 2026: HVAC System Upgrades – $42,000  
- 2027: Parking Garage Waterproofing – $28,000

**AI Risk Analysis:**  
- **Crisis Probability:** Medium risk in next 18 months  
- **Early Warning:** Reserve shortfall within 18 months  
- **Preventive Action Required:** Yes

**FUNDING RECOMMENDATIONS:**  
- **Option 1: Gradual Increase**: Increase monthly fees by $50/unit  
- **Option 2: Special Assessment**: $6,000/unit  
- **Option 3: Status Quo**: Risk Level HIGH, potential future assessment $545/unit

**NEXT STEPS:**  
1. Board review of options at March 15, 2025  
2. Board to vote on funding strategy  
3. Distribute meeting summary to all owners by March 20, 2025

**Questions?**  
Please contact me at [Email Address].

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Phone Number]`,

  // 9. Vendor Announcement
  'vendor-announcement': `Subject: New Service Provider – Maple Heights Condominiums – [Service Type]

Body:  
Dear Residents / Board Members,

We are pleased to announce that Maple Heights Condominiums has selected a new service provider for [Service Type].

**NEW VENDOR INFORMATION:**  
- **Company:** [Vendor Name]  
- **Service:** [Detailed Service Description]  
- **Start Date:** [Date]  
- **Contact:** [Vendor Contact Information]

**WHY THIS CHANGE:**  
[Brief explanation of selection reasoning]

**WHAT THIS MEANS FOR YOU:**  
- [Impact/Change 1]  
- [Impact/Change 2]  
- [Impact/Change 3]

**SERVICE SCHEDULE:**  
- [Regular service timing]  
- [Emergency contact procedures]  
- [Any special arrangements]

**TRANSITION PROCESS:**  
- [Timeline item 1]  
- [Timeline item 2]  
- [Timeline item 3]

**COST IMPACT:**  
[Annual savings or fee change details]

**YOUR FEEDBACK:**  
Please contact us with any questions or concerns.

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Phone Number]`,

  // 10. Policy Change
  'policy-change': `Subject: Important Policy Update – Maple Heights Condominiums – Effective [Date]

Body:  
Dear Residents / Board Members,

The Board of Directors has approved important policy changes for Maple Heights Condominiums, effective [Effective Date].

**POLICY CHANGES SUMMARY:**  
1. [Policy Area 1]: [Old rule] → [New rule] (Reason: [Justification])  
2. [Policy Area 2]: [Old rule] → [New rule] (Reason: [Justification])  
3. [Policy Area 3]: [Old rule] → [New rule] (Reason: [Justification])

**IMPLEMENTATION TIMELINE:**  
- Approved: [Date]  
- Notification: [Date]  
- Grace period begins: [Date]  
- Full enforcement: [Date]

**ENFORCEMENT:**  
- First violation: [Consequence]  
- Subsequent violations: [Escalated consequence]  
- Appeals process: [Procedure]

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Phone Number]`,

  // 11. Special Assessment
  'special-assessment': `Subject: IMPORTANT: Special Assessment Notice – Maple Heights Condominiums – $6,000

Body:  
Dear [Unit Owner],

The Board of Directors has approved a special assessment for Maple Heights Condominiums to address Roof Replacement and other urgent capital repairs.

**SPECIAL ASSESSMENT DETAILS:**  
- **Amount:** $6,000 per unit  
- **Your Unit:** [Unit Number] – Total Due: $6,000  
- **Due Date:** 2025-03-15  
- **Purpose:** To fund roof replacement, HVAC system upgrades, and professional services

**BREAKDOWN OF COSTS:**  
- Roof replacement – $85,000  
- HVAC emergency repairs – $42,000  
- Legal/engineering fees – $28,000  
- **Total Project Cost:** $155,000  
- **Cost Per Unit:** $6,000

**PAYMENT OPTIONS:**  
1. Full Payment – Pay $6,000 by April 30, 2025 (no interest)  
2. Payment Plan – Initial $2,000 by [Initial Payment Date], then $400/mo for 10 months (5% annual)

**CONSEQUENCES OF NON-PAYMENT:**  
- Late fees: $100 after [Late Fee Date]  
- Interest charges: 2% monthly  
- Lien placement on unit  
- Legal action for collection

**HOW TO PAY:**  
- Online: [Payment Portal]  
- Check: Mail to 1247 Maple Avenue, Toronto, ON M4K 1M7  
- In person: Mon–Fri, 9 AM–5 PM  
- Bank transfer: [Transfer Details]

**QUESTIONS OR FINANCIAL HARDSHIP:**  
Contact [Email Address] | [Phone Number]

**BOARD MEETING:**  
A special meeting was held on February 28, 2025 where this assessment was approved.

**PAYMENT DEADLINE:** 2025-03-15 – Please mark your calendar

Best regards,  
Sarah Chen  
On behalf of the Board of Directors  
Toronto Property Solutions  
[Phone Number]`,

  // 12. General Communication
  'general-communication': `Subject: Maple Heights Condominiums – [Communication Topic]

Body:  
Dear [Residents/Board Members],

I hope this message finds you well. I'm writing to update you on [general topic] for Maple Heights Condominiums.

**[Section 1 Heading]:**  
[Content for first topic]

**[Section 2 Heading]:**  
[Content for second topic]

**[Section 3 Heading]:**  
[Content for third topic]

**UPCOMING DATES TO REMEMBER:**  
- [Date]: [Event/Deadline]  
- [Date]: [Event/Deadline]  
- [Date]: [Event/Deadline]

**REMINDERS:**  
- [Reminder 1]  
- [Reminder 2]  
- [Reminder 3]

**CONTACT INFORMATION:**  
- General questions: [Email Address]  
- Emergency maintenance: [Emergency Contact]  
- Board communications: [Board Contact]

**NEXT COMMUNICATION:**  
Our next regular update will be sent [Timeframe]. If you have specific topics you'd like addressed, please contact us at [Email Address].

Thank you for being part of our community. Your cooperation and engagement help make Maple Heights Condominiums a great place to live.

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Phone Number]`,

  'owner-faq': `Dear [Owner Name],

Thank you for your question regarding Maple Heights. Below you'll find detailed answers to address your concerns.

**YOUR QUESTION:**
[Original question from owner]

**OUR RESPONSE:**

**[Topic Area 1]:**
[Detailed answer to specific question component]

**[Topic Area 2]:**
[Additional clarification if multi-part question]

**RELATED INFORMATION:**
You may also find these details helpful:
- [Related point 1]
- [Related point 2]
- [Related point 3]

**RELEVANT POLICIES:**
- [Policy reference if applicable]
- [Bylaw reference if applicable]
- [Regulatory requirement if applicable]

**ADDITIONAL RESOURCES:**
- Building documents: [Where to access]
- Board meeting minutes: [How to obtain]
- Policy handbook: [Reference location]

**NEXT STEPS:**
[If any action required from owner or management]

**STILL HAVE QUESTIONS?**
- Email us: [Contact Email]
- Office hours: [Office Hours]
- Next Board meeting: [Board Meeting Date]
- Phone consultation: [Contact Phone]

**SIMILAR QUESTIONS:**
If other owners have similar questions, we will address them in our next community newsletter on [Newsletter Date].

We appreciate your engagement and interest in building operations. Your questions help us improve communication for all residents.

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Contact Email] | [Phone Number]
`,
  'insurance-update': `Dear Board Members,

This notice provides important updates regarding Maple Heights’s insurance coverage, effective [Effective Date].

**INSURANCE POLICY SUMMARY:**

Coverage Type: [Property/Liability/Umbrella]  
Insurance Provider: [Company Name]  
Policy Number: [Policy Number]  
Effective Period: [Start Date] to [End Date]  
Annual Premium: $[Amount]

**WHAT’S CHANGING:**

Coverage Improvements:
- [Enhancement 1]: [Details]
- [Enhancement 2]: [Details]

Coverage Changes:
- [Change 1]: [Previous coverage] → [New coverage]

Deductibles:
- [Coverage Type]: $[Amount] (was $[Previous Amount])

**FINANCIAL IMPACT:**

Premium Change: [Increase/Decrease] of $[Amount]  
Cost per unit: [Increase/Decrease] of $[Amount]  
Effective Date: [Date]

**WHY THESE CHANGES:**  
[Explanation]

**CLAIMS PROCESS:**
- Report claims: [Contact Email]
- Emergency hotline: [Emergency Number]
- Required docs: [Claim Documentation Details]

**CERTIFICATE OF INSURANCE:**
- Request from: [Property Manager Name]
- Processing time: [Timeframe]

**REMINDERS:**

For Unit Owners:
- Covers common areas, not contents
- You should carry personal insurance
- Recommended liability: $[Amount]

For Board Members:
- Review policy: [Where]
- Committee meeting: [Date]
- Next insurance review: [Date]

**BROKER INFO:**  
[Broker Name]  
[Broker Email] | [Phone Number]  

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Contact Email]
`,
"construction-update": `
Dear Residents,

This is an update on the ongoing construction project at Maple Heights.

**PROJECT OVERVIEW:**
- Project Name: Parking Garage Waterproofing
- Start Date: [Start Date]
- Original Completion: [Date]
- Current Status: [Percentage]% complete
- Revised Completion: [Date if changed]

**WORK COMPLETED THIS PERIOD:**
- [Task 1]
- [Task 2]
- [Task 3]

**CURRENT PHASE:**  
[Phase Details]

**NEXT 2 WEEKS:**
- Week of [Date]: [Planned Work]
- Week of [Date]: [Planned Work]

**SCHEDULE:**  
[On Schedule / Delayed by X days]

**IMPACTS TO RESIDENTS:**
- Noise: [Level]
- Access: [Restrictions]
- Parking: [Status]
- Utilities: [Disruption Notice]

**SAFETY:**  
- Site secured  
- PPE required in affected zones  
- Emergency Contact: [Contractor Emergency Number]

**QUALITY CONTROL:**
- Inspections: [Inspector Name]  
- Meetings: Weekly on [Day]

**COMMUNICATION:**
- Project Manager: [Name + Contact]  
- Contractor: [Name + Contact]  
- Property Manager: Sarah Chen – [Contact Email]  
- Next Update: [Date]

Thank you for your patience during this important work.  

Best regards,  
Sarah Chen  
Toronto Property Solutions  
[Contact Email]`,
"board-resolution": `Dear Residents,

The Board of Directors of Maple Heights has adopted the following resolution at its meeting on [Date].

**RESOLUTION #2025-01 – Reserve Fund Strategy Adjustment**

MEETING DETAILS:  
- Date: [Date]  
- Time: [Time]  
- Type: Regular Meeting  
- Quorum: Yes – 4 of 5 Directors Present  
- Vote: 4 in favor, 1 opposed

**RESOLUTION TEXT:**
"WHEREAS the reserve fund is below recommended levels;  
WHEREAS major repairs are scheduled over the next 3 years;  
NOW THEREFORE BE IT RESOLVED THAT the board will adopt a phased fee increase strategy beginning March 2025."

**IMPACT TO RESIDENTS:**
- Monthly fees will increase $35/unit starting March 1, 2025  
- No special assessment planned for 2025  
- Detailed budget document available on request

**DOCUMENTATION:**
- Full Resolution: [Where to get it]  
- Meeting Minutes: [Access details]  
- Supporting Docs: [Docs list]

**NEXT BOARD MEETING:**  
- Date: March 15, 2025  
- Time: 2:00 PM  
- Location: Party Room + Zoom  

**QUESTIONS:**  
- Policy questions: [Contact Email]  
- Resolution impact: Sarah Chen – [Contact Email]  
- Legal inquiries: [Legal Contact if needed]

Certified by:  
[Board Secretary Name]  
Toronto Property Solutions  

[Contact Email] | [Phone Number]
`
};
